### ISSUE TITLE
Add infomix path in bashrc

### ISSUE THREAD

**Issue by norjuliana** [censof/ansible-deployment#143]
Add informix path in bashrc

**Comment by lowks** [comment]
Can put the exact string to add ka Dr. Strange ?

**Comment by norjuliana** [comment]
I already talk to Aldash,we might not need to add Informix into this file.I have to retest what the impact if i remove the lines he added.

instead add inside /etc/ld.so.conf.d/informix.conf

/opt/IBM/informix/lib
/opt/IBM/informix/lib/esql
/opt/IBM/informix/lib/msg

**Comment by norjuliana** [comment]
fixed by closing #168
