### ISSUE TITLE
find way to alter postgres shared memory shmmax and shmall

### ISSUE THREAD

**Issue by norjuliana** [censof/ansible-deployment#170]
having issue with shamall too small,causing postgres service wont start.

**Comment by lowks** [comment]
@norjuliana can you specify the too small value to aid with debugging this issue ?

**Comment by norjuliana** [comment]
@lowks  happen when postgresql service wont start and throw error about shared memory is not enough to start postgresql

**Comment by norjuliana** [comment]
Please refer to attached file
[sysctl_conf.txt](https://github.com/censof/ansible-deployment/files/877736/sysctl_conf.txt)
![postgresqstartfailed](https://cloud.githubusercontent.com/assets/19965406/24437562/4e56ad78-1474-11e7-8d0a-08acb15bb630.jpg)
