### ISSUE TITLE
rc.d section for uwsgi is unnecessary for Ubuntu

### ISSUE THREAD

**Issue by lowks** [censof/ansible-deployment#73]
rc.d section for uwsgi is unnecessary for Ubuntu so should be put into a when clause.

**Comment by norjuliana** [comment]
reference after research:
https://luxagraf.net/src/how-set-django-uwsgi-systemd-debian-8
http://serverfault.com/questions/775965/wiring-uwsgi-to-work-with-django-and-nginx-on-ubuntu-16-04
http://uwsgi-docs.readthedocs.io/en/latest/Systemd.html

**Comment by lowks** [comment]
Fixed by #61
