### ISSUE TITLE
Find out more about harakiri setting in uwsgi.ini

### ISSUE THREAD

**Issue by lowks** [censof/ansible-deployment#83]
Find out more about `harakiri` setting in our `uwsgi.ini`. Make the decision if we really need it or not. If we need it have to make it work. The code now comments out the `harakiri` settings.

Research:

- http://stackoverflow.com/questions/18602592/stop-uwsgi-performing-harakiri-seriously

- http://uwsgi-docs.readthedocs.io/en/latest/FAQ.html#what-is-harakiri-mode

Great resource with tips and tricks:

http://projects.unbit.it/uwsgi/wiki/TipsAndTricks

**Comment by norjuliana** [comment]
http://stackoverflow.com/questions/24127601/uwsgi-request-timeout-in-python
https://emptyhammock.com/projects/info/pyweb/uwsgi.html
