### ISSUE TITLE
change harakiri value in uwsgi.ini,keepalive_timeout 180

### ISSUE THREAD

**Issue by norjuliana** [censof/ansible-deployment#90]
change both value for harakiri in uwsgi.ini and nginx.conf to 180.

**Comment by lowks** [comment]
Does it work ?

**Comment by norjuliana** [comment]
it will solve large upload file issue as because the main issue is harakiri is set to low,the workers will respawn before file is finish uploading.value of harakirir and keepalive_timeout in nginx.conf must be equal.

**Comment by lowks** [comment]
Okay.

**Comment by norjuliana** [comment]
Aldash the one request this changes.He already tested it.

**Comment by lowks** [comment]
Okay then
